-- =============================================================================
-- Mawjood: PostgreSQL-specific objects. Load after db/schema.sql, before seed.sql.
-- SQLite equivalent: db/dialect/sqlite.sql
-- After seed.sql, run db/dialect/postgresql_sequences.sql.
-- =============================================================================

-- Identity columns: schema.sql declares portable "INTEGER PRIMARY KEY", which
-- auto-numbers in SQLite but not in PostgreSQL. BY DEFAULT keeps explicit ids
-- from seed.sql valid.
ALTER TABLE departments      ALTER COLUMN department_id   ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE users            ALTER COLUMN user_id         ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE offices          ALTER COLUMN office_id       ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE schedule_blocks  ALTER COLUMN block_id        ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE status_overrides ALTER COLUMN override_id     ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE appointments     ALTER COLUMN appointment_id  ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE conversations    ALTER COLUMN conversation_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE messages         ALTER COLUMN message_id      ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE notifications    ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY;
-- students.student_id and professors.professor_id copy users.user_id, so they
-- are deliberately not identity columns.

-- Double-booking guard, layer 2 (see db/dialect/sqlite.sql for the rationale).
CREATE OR REPLACE FUNCTION fn_appointments_no_overlap() RETURNS trigger AS $$
BEGIN
    IF NEW.status IN ('pending', 'approved') AND EXISTS (
        SELECT 1
        FROM appointments AS a
        WHERE a.professor_id = NEW.professor_id
          AND a.appointment_id IS DISTINCT FROM NEW.appointment_id
          AND a.status IN ('pending', 'approved')
          AND a.starts_at < NEW.ends_at
          AND NEW.starts_at < a.ends_at
    ) THEN
        RAISE EXCEPTION 'SLOT_TAKEN: overlapping appointment for this professor'
            USING ERRCODE = 'unique_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_appointments_no_overlap ON appointments;
CREATE TRIGGER trg_appointments_no_overlap
BEFORE INSERT OR UPDATE OF professor_id, starts_at, ends_at, status ON appointments
FOR EACH ROW EXECUTE FUNCTION fn_appointments_no_overlap();
